version: "2"

volumes:
  network_events_data:

services:
  monitor:
    build: ./monitor
    volumes:
      - network_events_data:/app/data
    environment:
      - "DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
    labels:
      # Security Warning: Enable access to host D-Bus:
      # This allows the container to interact with the host system and pose security risks if not properly managed.
      io.balena.features.dbus: "1"
